// Code generated by relspecgo. DO NOT EDIT.
package models

import (
	"database/sql"
	"fmt"
)

type ModelPublicAuditEvent struct {
	IDAuditEvent                        int64                     `gorm:"column:id_audit_event;type:bigserial;primaryKey;autoIncrement" json:"id_audit_event"`
	Action                              sql.NullInt16             `gorm:"column:action;type:smallint" json:"action"`
	Datetime                            sql.NullTime              `gorm:"column:datetime;type:timestamp;index:audit_event_datetime_idx" json:"datetime"`
	RIDUser                             sql.NullInt64             `gorm:"column:rid_user;type:bigint" json:"rid_user"`
	RowID                               sql.NullInt64             `gorm:"column:row_id;type:bigint;index:audit_event_row_idx" json:"row_id"`
	Tablename                           sql.NullString            `gorm:"column:tablename;type:text;index:audit_event_row_idx" json:"tablename"`
	RelRIDUser                          *ModelPublicUser          `gorm:"foreignKey:RIDUser;references:IDUser" json:"relriduser,omitempty"`               // Belongs to ModelPublicUser
	RelRIDAuditDetailPublicAuditDetails []*ModelPublicAuditDetail `gorm:"foreignKey:RIDAuditDetail" json:"relridauditdetailpublicauditdetails,omitempty"` // Has many ModelPublicAuditDetail
}

// TableName returns the table name for ModelPublicAuditEvent
func (m ModelPublicAuditEvent) TableName() string {
	return "public.audit_event"
}

// TableNameOnly returns the table name without schema for ModelPublicAuditEvent
func (m ModelPublicAuditEvent) TableNameOnly() string {
	return "audit_event"
}

// SchemaName returns the schema name for ModelPublicAuditEvent
func (m ModelPublicAuditEvent) SchemaName() string {
	return "public"
}

// GetID returns the primary key value
func (m ModelPublicAuditEvent) GetID() int64 {
	return int64(m.IDAuditEvent)
}

// GetIDStr returns the primary key as a string
func (m ModelPublicAuditEvent) GetIDStr() string {
	return fmt.Sprintf("%d", m.IDAuditEvent)
}

// SetID sets the primary key value
func (m ModelPublicAuditEvent) SetID(newid int64) {
	m.UpdateID(newid)
}

// UpdateID updates the primary key value
func (m *ModelPublicAuditEvent) UpdateID(newid int64) {
	m.IDAuditEvent = int64(newid)
}

// GetIDName returns the name of the primary key column
func (m ModelPublicAuditEvent) GetIDName() string {
	return "id_audit_event"
}

// GetPrefix returns the table prefix
func (m ModelPublicAuditEvent) GetPrefix() string {
	return "AEU"
}
