// Code generated by relspecgo. DO NOT EDIT.
package models

import (
	"database/sql"
	"fmt"
)

type ModelPublicUser struct {
	IDUser                       int64                     `gorm:"column:id_user;type:bigserial;primaryKey;autoIncrement" json:"id_user"`
	ClientID                     sql.NullString            `gorm:"column:client_id;type:text" json:"client_id"`
	ClientSecret                 sql.NullString            `gorm:"column:client_secret;type:text" json:"client_secret"`
	Email                        sql.NullString            `gorm:"column:email;type:text;uniqueIndex:user_email_uq" json:"email"`
	Name                         sql.NullString            `gorm:"column:name;type:text" json:"name"`
	Password                     sql.NullString            `gorm:"column:password;type:text" json:"password"`                        // Hashed SHA256 Password
	Role                         sql.NullString            `gorm:"column:role;type:text" json:"role"`                                // memeber/admin
	RelRIDUserPublicAccounts     []*ModelPublicAccount     `gorm:"foreignKey:RIDUser" json:"relriduserpublicaccounts,omitempty"`     // Has many ModelPublicAccount
	RelRIDUserPublicAuditEvents  []*ModelPublicAuditEvent  `gorm:"foreignKey:RIDUser" json:"relriduserpublicauditevents,omitempty"`  // Has many ModelPublicAuditEvent
	RelRIDUserPublicUserSessions []*ModelPublicUserSession `gorm:"foreignKey:RIDUser" json:"relriduserpublicusersessions,omitempty"` // Has many ModelPublicUserSession
}

// TableName returns the table name for ModelPublicUser
func (m ModelPublicUser) TableName() string {
	return "public.user"
}

// TableNameOnly returns the table name without schema for ModelPublicUser
func (m ModelPublicUser) TableNameOnly() string {
	return "user"
}

// SchemaName returns the schema name for ModelPublicUser
func (m ModelPublicUser) SchemaName() string {
	return "public"
}

// GetID returns the primary key value
func (m ModelPublicUser) GetID() int64 {
	return int64(m.IDUser)
}

// GetIDStr returns the primary key as a string
func (m ModelPublicUser) GetIDStr() string {
	return fmt.Sprintf("%d", m.IDUser)
}

// SetID sets the primary key value
func (m ModelPublicUser) SetID(newid int64) {
	m.UpdateID(newid)
}

// UpdateID updates the primary key value
func (m *ModelPublicUser) UpdateID(newid int64) {
	m.IDUser = int64(newid)
}

// GetIDName returns the name of the primary key column
func (m ModelPublicUser) GetIDName() string {
	return "id_user"
}

// GetPrefix returns the table prefix
func (m ModelPublicUser) GetPrefix() string {
	return "USE"
}
