// Code generated by relspecgo. DO NOT EDIT.
package models

import (
	"database/sql"
	"fmt"
)

type ModelPublicAccount struct {
	IDAccount                              int64                            `gorm:"column:id_account;type:bigint;primaryKey" json:"id_account"`
	Balance                                sql.NullFloat64                  `gorm:"column:balance;type:numeric(16,2)" json:"balance"`
	Name                                   sql.NullString                   `gorm:"column:name;type:text;uniqueIndex:index_2" json:"name"`
	RIDUser                                sql.NullInt64                    `gorm:"column:rid_user;type:bigint;uniqueIndex:index_2" json:"rid_user"`
	RelRIDUser                             *ModelPublicUser                 `gorm:"foreignKey:RIDUser;references:IDUser" json:"relriduser,omitempty"`              // Belongs to ModelPublicUser
	RelRIDAccountPublicAccountTransactions []*ModelPublicAccountTransaction `gorm:"foreignKey:RIDAccount" json:"relridaccountpublicaccounttransactions,omitempty"` // Has many ModelPublicAccountTransaction
}

// TableName returns the table name for ModelPublicAccount
func (m ModelPublicAccount) TableName() string {
	return "public.account"
}

// TableNameOnly returns the table name without schema for ModelPublicAccount
func (m ModelPublicAccount) TableNameOnly() string {
	return "account"
}

// SchemaName returns the schema name for ModelPublicAccount
func (m ModelPublicAccount) SchemaName() string {
	return "public"
}

// GetID returns the primary key value
func (m ModelPublicAccount) GetID() int64 {
	return int64(m.IDAccount)
}

// GetIDStr returns the primary key as a string
func (m ModelPublicAccount) GetIDStr() string {
	return fmt.Sprintf("%d", m.IDAccount)
}

// SetID sets the primary key value
func (m ModelPublicAccount) SetID(newid int64) {
	m.UpdateID(newid)
}

// UpdateID updates the primary key value
func (m *ModelPublicAccount) UpdateID(newid int64) {
	m.IDAccount = int64(newid)
}

// GetIDName returns the name of the primary key column
func (m ModelPublicAccount) GetIDName() string {
	return "id_account"
}

// GetPrefix returns the table prefix
func (m ModelPublicAccount) GetPrefix() string {
	return "ACC"
}
