// Code generated by relspecgo. DO NOT EDIT.
package models

import (
	"database/sql"
	"fmt"
)

type ModelPublicAccountTransaction struct {
	IDAccountTransaction int64               `gorm:"column:id_account_transaction;type:bigserial;primaryKey;autoIncrement" json:"id_account_transaction"`
	Action               sql.NullString      `gorm:"column:action;type:text" json:"action"` // spend/earn
	Amount               sql.NullFloat64     `gorm:"column:amount;type:numeric(16,2)" json:"amount"`
	Reference            sql.NullString      `gorm:"column:reference;type:text;uniqueIndex:index_2" json:"reference"`
	RIDAccount           sql.NullInt64       `gorm:"column:rid_account;type:bigint;uniqueIndex:index_2" json:"rid_account"`
	TransactionDatetime  sql.NullTime        `gorm:"column:transaction_datetime;type:timestamp;index:index_3" json:"transaction_datetime"`
	RelRIDAccount        *ModelPublicAccount `gorm:"foreignKey:RIDAccount;references:IDAccount" json:"relridaccount,omitempty"` // Belongs to ModelPublicAccount
}

// TableName returns the table name for ModelPublicAccountTransaction
func (m ModelPublicAccountTransaction) TableName() string {
	return "public.account_transaction"
}

// TableNameOnly returns the table name without schema for ModelPublicAccountTransaction
func (m ModelPublicAccountTransaction) TableNameOnly() string {
	return "account_transaction"
}

// SchemaName returns the schema name for ModelPublicAccountTransaction
func (m ModelPublicAccountTransaction) SchemaName() string {
	return "public"
}

// GetID returns the primary key value
func (m ModelPublicAccountTransaction) GetID() int64 {
	return int64(m.IDAccountTransaction)
}

// GetIDStr returns the primary key as a string
func (m ModelPublicAccountTransaction) GetIDStr() string {
	return fmt.Sprintf("%d", m.IDAccountTransaction)
}

// SetID sets the primary key value
func (m ModelPublicAccountTransaction) SetID(newid int64) {
	m.UpdateID(newid)
}

// UpdateID updates the primary key value
func (m *ModelPublicAccountTransaction) UpdateID(newid int64) {
	m.IDAccountTransaction = int64(newid)
}

// GetIDName returns the name of the primary key column
func (m ModelPublicAccountTransaction) GetIDName() string {
	return "id_account_transaction"
}

// GetPrefix returns the table prefix
func (m ModelPublicAccountTransaction) GetPrefix() string {
	return "ATC"
}
