// Code generated by relspecgo. DO NOT EDIT.
package models

import (
	"database/sql"
	"fmt"
)

type ModelPublicUserSession struct {
	IDUserSession int64            `gorm:"column:id_user_session;type:bigserial;primaryKey;autoIncrement" json:"id_user_session"`
	Authtoken     sql.NullString   `gorm:"column:authtoken;type:text" json:"authtoken"`
	Createdat     sql.NullTime     `gorm:"column:createdat;type:timestamp" json:"createdat"`
	Expiresat     sql.NullTime     `gorm:"column:expiresat;type:timestamp" json:"expiresat"`
	RIDUser       sql.NullInt64    `gorm:"column:rid_user;type:bigint" json:"rid_user"`
	RelRIDUser    *ModelPublicUser `gorm:"foreignKey:RIDUser;references:IDUser" json:"relriduser,omitempty"` // Belongs to ModelPublicUser
}

// TableName returns the table name for ModelPublicUserSession
func (m ModelPublicUserSession) TableName() string {
	return "public.user_session"
}

// TableNameOnly returns the table name without schema for ModelPublicUserSession
func (m ModelPublicUserSession) TableNameOnly() string {
	return "user_session"
}

// SchemaName returns the schema name for ModelPublicUserSession
func (m ModelPublicUserSession) SchemaName() string {
	return "public"
}

// GetID returns the primary key value
func (m ModelPublicUserSession) GetID() int64 {
	return int64(m.IDUserSession)
}

// GetIDStr returns the primary key as a string
func (m ModelPublicUserSession) GetIDStr() string {
	return fmt.Sprintf("%d", m.IDUserSession)
}

// SetID sets the primary key value
func (m ModelPublicUserSession) SetID(newid int64) {
	m.UpdateID(newid)
}

// UpdateID updates the primary key value
func (m *ModelPublicUserSession) UpdateID(newid int64) {
	m.IDUserSession = int64(newid)
}

// GetIDName returns the name of the primary key column
func (m ModelPublicUserSession) GetIDName() string {
	return "id_user_session"
}

// GetPrefix returns the table prefix
func (m ModelPublicUserSession) GetPrefix() string {
	return "USS"
}
