// Code generated by relspecgo. DO NOT EDIT.
package models

import (
	"database/sql"
	"fmt"
)

type ModelPublicAuditDetail struct {
	IDAuditDetail     int64                  `gorm:"column:id_audit_detail;type:bigserial;primaryKey;autoIncrement" json:"id_audit_detail"`
	ColumnName        sql.NullString         `gorm:"column:column_name;type:text" json:"column_name"`
	ColumnValue       sql.NullString         `gorm:"column:column_value;type:text" json:"column_value"`
	RIDAuditDetail    sql.NullInt64          `gorm:"column:rid_audit_detail;type:bigint" json:"rid_audit_detail"`
	RelRIDAuditDetail *ModelPublicAuditEvent `gorm:"foreignKey:RIDAuditDetail;references:IDAuditEvent" json:"relridauditdetail,omitempty"` // Belongs to ModelPublicAuditEvent
}

// TableName returns the table name for ModelPublicAuditDetail
func (m ModelPublicAuditDetail) TableName() string {
	return "public.audit_detail"
}

// TableNameOnly returns the table name without schema for ModelPublicAuditDetail
func (m ModelPublicAuditDetail) TableNameOnly() string {
	return "audit_detail"
}

// SchemaName returns the schema name for ModelPublicAuditDetail
func (m ModelPublicAuditDetail) SchemaName() string {
	return "public"
}

// GetID returns the primary key value
func (m ModelPublicAuditDetail) GetID() int64 {
	return int64(m.IDAuditDetail)
}

// GetIDStr returns the primary key as a string
func (m ModelPublicAuditDetail) GetIDStr() string {
	return fmt.Sprintf("%d", m.IDAuditDetail)
}

// SetID sets the primary key value
func (m ModelPublicAuditDetail) SetID(newid int64) {
	m.UpdateID(newid)
}

// UpdateID updates the primary key value
func (m *ModelPublicAuditDetail) UpdateID(newid int64) {
	m.IDAuditDetail = int64(newid)
}

// GetIDName returns the name of the primary key column
func (m ModelPublicAuditDetail) GetIDName() string {
	return "id_audit_detail"
}

// GetPrefix returns the table prefix
func (m ModelPublicAuditDetail) GetPrefix() string {
	return "ADU"
}
